name: Java CI/CD

on:
  pull_request: 
    branches: [main]

  push:
    branches: [main]


jobs:
  build_and_test:
    runs-on: windows_latest

  steps:
    - name: checkout
      uses: action/checkout@v3

    - name: setup java 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: build with maven 
      uses: mvn clean install

    - name: run scripts
      uses: mvn test

    - name: docker build image
      uses: docker build -t petclinic-app
    
    
    

  

  
